const items = 
db.items.insertMany([
  {
    name: "Voyag Stuff Penny Loafers",
    description: "Loafers kasual dengan motif bintang khas, unisex, dan nyaman.",
    imgSrc: "https://example.com/images/voyag_stuff_penny_loafers.png",
    price: 250000,
    category: "casual shoes",
    isNew: true,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Brygan Brogues",
    description: "Classic brogues dengan jahitan rapi dari kulit sintetis, elegan untuk formal.",
    imgSrc: "https://example.com/images/brygan_brogues.png",
    price: 300000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Floody Blue Suede Sneakers",
    description: "Sneakers kasual bertekstur suede, tersedia untuk pria, wanita, dan anak-anak.",
    imgSrc: "https://example.com/images/floody_blue_suede_sneakers.png",
    price: 350000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "all",
  },
  {
    name: "Pijakbumi Kotta Hybrid",
    description: "Sneakers sustainable berbahan eceng gondok & sabut kelapa, eco-friendly dan stylish.",
    imgSrc: "https://example.com/images/pijakbumi_kotta_hybrid.png",
    price: 450000,
    category: "sustainable shoes",
    isNew: true,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Geoff Max Vulcanized Sneaker",
    description: "Sneakers kasual berbahan kanvas, desain mirip street style klasik.",
    imgSrc: "https://example.com/images/geoff_max_vulcanized_sneaker.png",
    price: 300000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Ventela New Public Low",
    description: "Sneakers vulkanisir berkualitas, insole ultralite foam, nyaman untuk daily wear.",
    imgSrc: "https://example.com/images/ventela_new_public_low.png",
    price: 300000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Brodo Formal Leather",
    description: "Sepatu kulit formal premium, cocok untuk acara resmi ataupun kantor.",
    imgSrc: "https://example.com/images/brodo_formal_leather.png",
    price: 550000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Brodo Casual Sneaker",
    description: "Sneakers kasual dari Brodo dengan tampilan elegan dan bahan berkualitas.",
    imgSrc: "https://example.com/images/brodo_casual_sneaker.png",
    price: 400000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "NAH Project Sneaker Minimalist",
    description: "Sneakers minimalis modern, ringan dan empuk—favorit anak muda.",
    imgSrc: "https://example.com/images/nah_project_sneaker_minimalist.png",
    price: 450000,
    category: "minimalist shoes",
    isNew: true,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Fortuna Leather Oxford",
    description: "Oxford kulit formal berkelas, bahan full‑grain leather, kualitas Eropa.",
    imgSrc: "https://example.com/images/fortuna_leather_oxford.png",
    price: 800000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Koku Footwear Derby",
    description: "Derby kulit buatan tangan, tahan lama dan elegan dari Cibaduyut Bandung.",
    imgSrc: "https://example.com/images/koku_footwear_derby.png",
    price: 500000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Txture Handcrafted Boots",
    description: "Boots kulit handcrafted, berkualitas tinggi dan detail superior.",
    imgSrc: "https://example.com/images/txture_handcrafted_boots.png",
    price: 650000,
    category: "boots",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Buccheri Slip-On Casual",
    description: "Slip‑on elegan dari Buccheri, terbuat dari kulit, nyaman dan stylish.",
    imgSrc: "https://example.com/images/buccheri_slip_on_casual.png",
    price: 550000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Heiden Heritage Canvas",
    description: "Sneakers retro ala Samba, bahan canvas/suede, desain trendi dan nyaman.",
    imgSrc: "https://example.com/images/heiden_heritage_canvas.png",
    price: 400000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Exodos57 Biker Sneaker",
    description: "Sneakers ala anak motor, kuat dan maskulin, untuk gaya gahar.",
    imgSrc: "https://example.com/images/exodos57_biker_sneaker.png",
    price: 700000,
    category: "biker shoes",
    isNew: false,
    gender: "male",
    ageGroup: "adult",
  },
  {
    name: "Veectory Minimalist Sneaker",
    description: "Sneakers minimalis dengan inspirasi Common Projects, modern dan sleek.",
    imgSrc: "https://example.com/images/veectory_minimalist_sneaker.png",
    price: 300000,
    category: "minimalist shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Patrobas Ivan Vulcanized",
    description: "Sneakers vulkanized bertema edgy, desain bold dan nyaman.",
    imgSrc: "https://example.com/images/patrobas_ivan_vulcanized.png",
    price: 350000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Walko Bold Sneaker",
    description: "Sneaker dengan desain berani dan unik, kualitas mendekati brand luar.",
    imgSrc: "https://example.com/images/walko_bold_sneaker.png",
    price: 400000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Indiverse Leather Slip-On",
    description: "Slip-on premium dengan nuansa budaya Indonesia, formal & kasual cocok.",
    imgSrc: "https://example.com/images/indiverse_leather_slip_on.png",
    price: 500000,
    category: "casual shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Guten Inc Chunky Shoes",
    description: "Daddy shoes bergaya chunky dari Guten, nyaman dan trendi.",
    imgSrc: "https://example.com/images/guten_inc_chunky_shoes.png",
    price: 450000,
    category: "chunky shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Kythshoes Custom Leather",
    description: "Sepatu kulit custom dengan full grain, fleksibel dan tahan lama.",
    imgSrc: "https://example.com/images/kythshoes_custom_leather.png",
    price: 550000,
    category: "custom shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Cardinal Classic Leather",
    description: "Sepatu kulit klasik dengan desain sederhana namun elegan.",
    imgSrc: "https://example.com/images/cardinal_classic_leather.png",
    price: 450000,
    category: "classic shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Amble Slipper Vintage",
    description: "Slipper kulit vintage yang nyaman dan stylish untuk santai.",
    imgSrc: "https://example.com/images/amble_slipper_vintage.png",
    price: 400000,
    category: "slippers",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Yongki Komaladi High Heels",
    description: "High heels elegan dari Yongki Komaladi, cocok untuk wanita stylish.",
    imgSrc: "https://example.com/images/yongki_komaladi_high_heels.png",
    price: 600000,
    category: "high heels",
    isNew: false,
    gender: "female",
    ageGroup: "adult",
  },
  {
    name: "Portee Chunky Sneaker",
    description: "Sneaker chunky kulit asli, kuat dan fashionable untuk pria/wanita.",
    imgSrc: "https://example.com/images/portee_chunky_sneaker.png",
    price: 550000,
    category: "chunky shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Nappa Milano Oxford Classic",
    description: "Sepatu formal berbahan kulit premium, desain vintage dan timeless cocok untuk pria/wanita.",
    imgSrc: "https://nappamilano.id/cdn/shop/files/1_c52a1e56-2d9a-4f34-b772-d939bee87bd1_grande.png?v=1751943848",
    price: 650000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Portee Goods Loafers",
    description: "Loafers klasik berbahan kulit premium, ideal untuk gaya formal dan semi-formal.",
    imgSrc: "https://d2kchovjbwl1tk.cloudfront.net/vendor/11421/product/original_loafers_boots_cover_cw_1753771916213.jpg",
    price: 500000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Lederweren Monkstrap",
    description: "Monkstrap elegan dengan bahan kulit, cocok untuk suasana formal maupun smart casual.",
    imgSrc: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/107/MTA-165639607/brd-44261_lederweren-leder-monkstrap-full-black-sepatu-kulit-pria-loafer-sepatu-formal-pria-black-edition_full01-400d6fc4.jpg",
    price: 400000,
    category: "formal shoes",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Jovem Studio Loaferboi",
    description: "Loafer unik dengan aksen smiley, desain santai namun stylish.",
    imgSrc: "https://jovemstudio.com/cdn/shop/files/LOAFERBOI-BLACK_1.png?v=1706000256&width=1200",
    price: 1000000,
    category: "casual shoes",
    isNew: true,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: "Amble Chelsea Boots",
    description: "Boots kulit handmade dengan sentuhan vintage, nyaman dan solid.",
    imgSrc: "https://images.outdoorandcountry.co.uk/image/upload/e_trim%3A2/bo_8px_solid_white/c_pad%2Cb_white%2Cw_511%2Ch_613%2Cf_auto%2Cq_auto%2Cdpr_2/v1751280602/product/422902.jpg",
    price: 600000,
    category: "boots",
    isNew: false,
    gender: "unisex",
    ageGroup: "adult",
  },
  {
    name: 'Nike Air Zoom Pegasus 38',
    description: 'Nike Air Zoom Pegasus 38 kembali untuk memberi Anda semangat dalam melangkah, melompat, dan berjingkrak menggunakan busa responsif yang sama seperti pendahulunya. Bagian atas sepatu berbahan mesh bersirkulasi udara memadukan kenyamanan dan daya tahan yang Anda inginkan, plus ruang gerak yang lebih leluasa untuk jari-jari kaki Anda.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9005c997-949f-4c9f-af77-32e82e214d31/NIKE+AIR+ZOOM+PEGASUS+38+%28GS%29.png',
    price: 1200000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: 'Nike Air Max 270',
    description: 'Sepatu gaya hidup pertama Nike, Air Max, menghadirkan gaya, kenyamanan, dan sikap berani dalam Nike Air Max 270. Desainnya terinspirasi dari ikon-ikon Air Max, menampilkan inovasi terhebat Nike dengan jendela besar dan rangkaian warna-warna segar.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e07987ed-96da-422f-beb4-8e9c7e120eb2/W+AIR+MAX+270.png',
    price: 1450000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: "Nike Air Force 1 '07",
    description: 'Gaya klasik dengan siluet ikonik.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ab0eea11-b4de-4eb8-9bde-dfe6cee58ae5/WMNS+AIR+FORCE+1+%2707+LX.png',
    price: 1300000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: "Nike Blazer Mid '77 Vintage",
    description: 'Nyaman, tahan lama, dan tak lekang oleh waktu—tentu saja, sepatu ini menjadi nomor satu. Konstruksi klasik tahun 80-an dipadukan dengan detail yang berani untuk gaya yang tak lekang oleh waktu, baik saat Anda di lapangan maupun saat bepergian.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7f942d0f-da99-4522-b8f7-6954db95bc77/blazer-mid-77-vintage-mens-shoes.png',
    price: 1250000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: 'Nike React Infinity Run Flyknit',
    description: 'Bantalan maksimal memberikan kenyamanan ekstra untuk lari sehari-hari. Nikmati platform lembut berbentuk rocker yang terbuat dari busa ReactX baru di bawah kaki, serta kerah dan lidah sepatu yang sangat nyaman untuk rasa nyaman. Selain itu, membran tahan air ditambahkan pada versi ini untuk membantu Anda tetap kering.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6d33c68e-def9-4231-abdd-64447e58764c/W+NIKE+REACTX+INFINITY+RUN+4.png',
    price: 1600000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: 'Nike Air VaporMax Flyknit 3',
    description: 'Nike Phantom Run 2 menawarkan fleksibilitas bagi pelari sehari-hari. Berdasarkan fondasi pendahulunya, sepatu ini mengembangkan desain tanpa tali dengan menambahkan topangan aman yang terasa seperti "menghilang" di kaki Anda. Lebih banyak busa berarti bantalan yang lebih baik, membuat Anda tetap nyaman saat berlari.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ec51a428-7dc3-42db-a8d5-b5ee5a2e7830/AIR+VAPORMAX+2023+FK.png',
    price: 2200000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: 'Nike Vaporfly 4',
    description: 'Vaporfly 4 adalah sepatu lari yang ramping, tangguh, dan tangguh. Kami mengurangi bobot di midsole, outsole, dan bagian atas sepatu dari Vaporfly 3, tanpa mengorbankan performa. Hasilnya adalah sepatu balap serba guna yang lebih ringan dan lebih bertenaga, yang dapat diandalkan dari lari satu mil hingga maraton.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8c77c5c8-1067-4cb2-9dbe-ea596b6028a0/ZOOMX+VAPORFLY+NEXT%25+4.png',
    price: 3500000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
  {
    name: 'Nike Alphafly 3',
    description: 'Dirancang khusus untuk kecepatan maraton, Alphafly 3 membantu Anda melampaui apa yang Anda bayangkan. Tiga teknologi inovatif mendukung lari Anda: unit Air Zoom dosis ganda membantu Anda melangkah ke langkah berikutnya; pelat serat karbon sepanjang kaki membantu Anda maju dengan mudah; dan midsole busa ZoomX dari ujung kaki hingga ujung kaki membantu Anda tetap segar dari awal hingga 26,2. Saatnya meninggalkan rekor pribadi lama Anda.',
    imgSrc: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a1919d1d-3bd8-47ae-9f83-2928dab2245c/AIR+ZOOM+ALPHAFLY+NEXT%25+3.png',
    price: 4200000,
    category: 'shoes',
    gender: 'unisex',
    ageGroup: 'adult',
  },
]);
